<?xml version="1.0"?>
<robot name="maccepa" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="maccepa_camdisk" params="name length material">

    <!-- massless (almost) visual bar -->
    <link name="${name}">

      <inertial>
        <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
        <mass value="0.001"/>
        <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
      </inertial>

      <visual>
        <!--<origin xyz="${length/2} 0 0" rpy="0 0 0"/>-->
        <geometry>
          <!--<box size="${length} 0.005 0.005"/>-->
          <mesh filename="package://maccepa_description/stl/camdisk.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="${material}"/>
      </visual>

      <!-- no collision -->

    </link>
  </xacro:macro>

</robot>
