maccepa:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 250

  # Position Controllers ---------------------------------------
  wrist_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist
    pid: {p: 1000.0, i: 0.0, d: 0.0}
